# Generated by Django 2.1.7 on 2019-03-18 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Circuit', max_length=100)),
                ('description', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(default='Exercise', max_length=100)),
                ('minutes', models.IntegerField(default=0)),
                ('seconds', models.IntegerField(default=0)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circuit', to='circuit.Circuit')),
            ],
        ),
    ]
