# Generated by Django 2.1.7 on 2019-03-18 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circuit', '0002_circuit_workouts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuit',
            name='workouts',
        ),
        migrations.AddField(
            model_name='circuit',
            name='fullcircuit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout', to='circuit.Workout'),
        ),
    ]
