# Generated by Django 2.1.7 on 2019-03-18 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuit', '0003_auto_20190318_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuit',
            name='fullcircuit',
        ),
    ]
